title: David Rau
position: Ph.D. Student
affiliation: University of Amsterdam, ILLC
email: d.m.rau (at) uva.nl
keywords: minimal academic
google_scholar: https://scholar.google.nl/citations?user=lz-VGnoAAAAJ
github_link: https://github.com/davidmrau
linkedin: https://www.linkedin.com/in/davidmrau/
avatar: ./assets/img/avatar.jpeg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description:  Academic personal homepage David Rau.
canonical: 
remote_theme: yaoyao-liu/strata-academic
